### ISSUE TITLE
Writing the same REL_GLOBALID to all features

### ISSUE THREAD

**Issue by jhuillery** [bnadler/Append-Features-With-Attachments#1]
Hello,

I'm attempting to use your script to append features with attachments from a source feature class to a target feature class.  When I run the script, It is taking the GLOBAL_ID created for the first feature in the Target feature class and overwriting all REL_GLOBALID records in the source attachment table with that GLOBAL_ID, resulting in all attachments being attached to the first feature in the target feature class.  I have made no modifications to your script other than the updateFeatureClass and targetFeatureClass variables.  

Thanks,

John

**Comment by bnadler** [comment]
Hi John.

That's definitely not what is supposed to happen.
Thanks for the report. I will look through this tool and let you know what I find.



Ben Nadler | Esri Professional Services | Technical Analyst – Utilities, Telecom, & Energy
C: 303.884.9323 | O: 303.443.7779 X8278
Sent from my phone


-------- Original message --------

**Comment by bnadler** [comment]
I made some simplifications to the code which fixed this issue, as well as improved performance.
Try it out now.
