### ISSUE TITLE
Question: Any examples on how to use?

### ISSUE THREAD

**Issue by tpcolson** [bnadler/Append-Features-With-Attachments#2]
This seems like JUST what I was looking for, but I'm having a hard time figuring out how to use it! Any examples on how to get it running? And...does this append from an AGOL source to a non AGOL source, eg. sync newly edited/added items in an AGOL hosted FS to a fire-walled SDE FC? Just one direction, or can this work in both directions?

**Comment by bnadler** [comment]
This tool is designed to take 2 identical feature classes existing in two geodatabases and append one to the other, while also appending attachments
This is designed to work with any geodatabase

You have to first download the features from AGOL/Portal in a file GDB format.  There is an existing script on the WIKI site that does this

In the script I have 2 different geodatabases with the same FC in each.
The scenario is that the AGOL FC has all NEW features.  You could write some methods to filter the features depending on your use case.

The target is the existing enterprise GDB, and the update GDB is the one exported from a hosted feature service in AGOL

Simply enter the path of the feature classes in the script on line 121 & 122


[cid:image002.jpg@01D0BAED.F059B210]

Sincerely,


[cid:image001.png@01D007E6.EAD9F710]Ben Nadler | Esri Professional Services | Technical Analyst | Utilities, Telecom, & Energy

O: 303.449.7779 ext. 8278 | C: 303.884.9323 | E: bnadler@esri.com<mailto:bnadler@esri.com> | esri.com/services<www.esri.com/services>

**Comment by johngillham** [comment]
I'm also having issues getting this to run.  (Excuse the ignorance here, I'm unfamiliar with python.)  Is it just lines 121 & 122 that have to be set to my gdb\FC?  Does anything have to be set for "def buildWhereClauseFromList(OriginTable, PrimaryKeyField, valueList):"?  I set lines 121&122 & tried to run it in IDLE, but it keeps saying invalid syntax?  Any ideas?

Ideally it'd be great to parameterize it to just be able to add into ArcToolbox as a runnable script? Guessing once I get it running I can just replace those 2 lines with: updateFeatureClass = sys.argv[0] and targetFeatureClass = sys.argv[1]?

**Comment by sarojthapa60** [comment]
Hey  @bnadler , I am trying to append a geodatabase into an existing geodatabse. Both of them have attachments. I assigned the path of both "updateFeatureClass" and "targetFeatureClass". However, I get the Runtime error saying 
Runtime error 
Traceback (most recent call last):
  File "<string>", line 126, in <module>
  File "<string>", line 122, in main
  File "<string>", line 79, in appendFeatures
TypeError: tuple indices must be integers, not NoneType

Thanks

**Comment by bnadler** [comment]
Hi Saroj.
Your email says “append a geodatabase”
Are you entering the geodatabase path parameter or the individual feature class within the geodatabase as the parameter? It should be the feature class.

**Comment by sarojthapa60** [comment]
Thank you for your prompt response. I have provided the path of the feature class.  The format is  r”C:\Users\Foldername\GeodatabaseName\FeatureClassName.

I even changed the REL_GLOBALID to REL_OBJECTID on lines 115 and 121. Regardless I get the same error message.

Thank You

**Comment by bnadler** [comment]
I would need to reproduce  with your data.
Can you upload a sample?



Ben Nadler | Esri Professional Services | Technical Analyst – Utilities, Telecom, & Energy
C: 303.884.9323 | O: 303.449.7779 X8278
[cid:storage_emulated_0_DCIM_image002_png_1454429193608]  |  Sent from my phone


-------- Original message --------
