### ISSUE TITLE
Triplicate attachments, and not updating line features

### ISSUE THREAD

**Issue by willhakai** [bnadler/Append-Features-With-Attachments#3]
Hi, I am glad you put this script together, it is exactly what I have been looking for!

I have been having a couple of issues though.
1. When updating points features, the attachments from the update features come in triplicate (although the existing features in the target don't get tripled)
2.When I run the script on line features, it doesn't seem to bring the update lines into the target features.

Any thoughts?

Thanks.

**Comment by bnadler** [comment]
The geometry type has no bearing on the process.

Maybe prost a sample of the data?



Ben Nadler | Esri Professional Services | Technical Analyst – Utilities, Telecom, & Energy
C: 303.884.9323 | O: 303.443.7779 X8278
Sent from my phone


-------- Original message --------

**Comment by bnadler** [comment]
Fyi I should mention that this is designed to load new features, it is not designed to handle updated to existing features.



Ben Nadler | Esri Professional Services | Technical Analyst – Utilities, Telecom, & Energy
C: 303.884.9323 | O: 303.443.7779 X8278
Sent from my phone


-------- Original message --------

**Comment by willhakai** [comment]
I was using it to update existing features on AGOL with a database of
features collected with Arc Collector (there was a problem with too many
files not syncing, which is why I used your script). My workflow was this:
Download the existing (target) features in a gdb from AGOL, convert the gdb
of collected features to the exact same schema as the target features, run
your script to merge the update features with the target features.
I will put together some sample data for you.

On Fri, Jul 17, 2015 at 5:21 PM, Ben Nadler <notifications@github.com>
wrote:

> Fyi I should mention that this is designed to load new features, it is not
> designed to handle updated to existing features.
>
>
>
> Ben Nadler | Esri Professional Services | Technical Analyst – Utilities,
> Telecom, & Energy
> C: 303.884.9323 | O: 303.443.7779 X8278
> Sent from my phone
>
>
> -------- Original message --------
> From: Will McInnes <notifications@github.com>
> Date: 07/17/2015 3:42 PM (GMT-07:00)
> To: bnadler/Append-Features-With-Attachments <
> Append-Features-With-Attachments@noreply.github.com>
> Subject: [Append-Features-With-Attachments] Triplicate attachments, and
> not updating line features (#3)
>
>
> Hi, I am glad you put this script together, it is exactly what I have been
> looking for!
>
> I have been having a couple of issues though.
> 1. When updating points features, the attachments from the update features
> come in triplicate (although the existing features in the target don't get
> tripled)
> 2.When I run the script on line features, it doesn't seem to bring the
> update lines into the target features.
>
> Any thoughts?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/bnadler/Append-Features-With-Attachments/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnadler/Append-Features-With-Attachments/issues/3#issuecomment-122459841>
> .
>



-- 
Will McInnes,
IT Specialist
Hakai Institute <http://www.hakai.org/>

**Comment by willhakai** [comment]
[Here is the data|https://drive.google.com/file/d/0B2UGXrmwnj6ZRHJqQW4tS1BzV1U/view?usp=sharing] I am working with. Try running it and let me know if you have any success, or if you have any ideas. I appreciate your help!

**Comment by bnadler** [comment]
You have some object extension on the features?
I cannot edit them without error.

I ran the script against some other data and did not see the duplicated records.
Check your extensions / data

Remember, this tool will append everything from the update to the target, so you need to make sure you are not- re-appending the same features/attachments  again and again.
That will look like the attachments are getting duplicated.

Sincerely,


[cid:image001.png@01D007E6.EAD9F710]Ben Nadler | Esri Professional Services | Technical Analyst | Utilities, Telecom, & Energy

O: 303.449.7779 ext. 8278 | C: 303.884.9323 | E: bnadler@esri.com<mailto:bnadler@esri.com> | esri.com/services<www.esri.com/services>

**Comment by willhakai** [comment]
Thanks Ben, I will look into the extensions and data. It is not duplicating
the features, just the attachments. There are definitely not any duplicates
already existing in the update. When I simulate the process of your script
manually (using append, creating temporary global ids etc.) the process
works fine. If I have this problem in the future, I will try it with some
different data. Thanks for your time.

On Mon, Jul 20, 2015 at 5:19 PM, Ben Nadler <notifications@github.com>
wrote:

> You have some object extension on the features?
> I cannot edit them without error.
>
> I ran the script against some other data and did not see the duplicated
> records.
> Check your extensions / data
>
> Remember, this tool will append everything from the update to the target,
> so you need to make sure you are not- re-appending the same
> features/attachments again and again.
> That will look like the attachments are getting duplicated.
>
> Sincerely,
>
>
> [cid:image001.png@01D007E6.EAD9F710]Ben Nadler | Esri Professional
> Services | Technical Analyst | Utilities, Telecom, & Energy
>
> O: 303.449.7779 ext. 8278 | C: 303.884.9323 | E: bnadler@esri.com<mailto:
> bnadler@esri.com> | esri.com/services<www.esri.com/services>
>
>
> From: Will McInnes [mailto:notifications@github.com]
> Sent: Monday, July 20, 2015 1:36 PM
> To: bnadler/Append-Features-With-Attachments
> Cc: Ben Nadler
> Subject: Re: [Append-Features-With-Attachments] Triplicate attachments,
> and not updating line features (#3)
>
> I was using it to update existing features on AGOL with a database of
> features collected with Arc Collector (there was a problem with too many
> files not syncing, which is why I used your script). My workflow was this:
> Download the existing (target) features in a gdb from AGOL, convert the
> gdb
> of collected features to the exact same schema as the target features, run
> your script to merge the update features with the target features.
> I will put together some sample data for you.
>
> On Fri, Jul 17, 2015 at 5:21 PM, Ben Nadler <notifications@github.com
> <mailto:notifications@github.com>>
> wrote:
>
> > Fyi I should mention that this is designed to load new features, it is
> not
> > designed to handle updated to existing features.
> >
> >
> >
> > Ben Nadler | Esri Professional Services | Technical Analyst – Utilities,
> > Telecom, & Energy
> > C: 303.884.9323 | O: 303.443.7779 X8278
> > Sent from my phone
> >
> >
> > -------- Original message --------
> > From: Will McInnes <notifications@github.com<mailto:
> notifications@github.com>>
> > Date: 07/17/2015 3:42 PM (GMT-07:00)
> > To: bnadler/Append-Features-With-Attachments <
> > Append-Features-With-Attachments@noreply.github.com<mailto:
> Append-Features-With-Attachments@noreply.github.com>>
> > Subject: [Append-Features-With-Attachments] Triplicate attachments, and
> > not updating line features (#3)
> >
> >
> > Hi, I am glad you put this script together, it is exactly what I have
> been
> > looking for!
> >
> > I have been having a couple of issues though.
> > 1. When updating points features, the attachments from the update
> features
> > come in triplicate (although the existing features in the target don't
> get
> > tripled)
> > 2.When I run the script on line features, it doesn't seem to bring the
> > update lines into the target features.
> >
> > Any thoughts?
> >
> > Thanks.
> >
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/bnadler/Append-Features-With-Attachments/issues/3>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/bnadler/Append-Features-With-Attachments/issues/3#issuecomment-122459841>
>
> > .
> >
>
>
>
> --
> Will McInnes,
> IT Specialist
> Hakai Institute <http://www.hakai.org/>
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/bnadler/Append-Features-With-Attachments/issues/3#issuecomment-123000951>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bnadler/Append-Features-With-Attachments/issues/3#issuecomment-123104655>
> .
>



-- 
Will McInnes,
IT Specialist
Hakai Institute <http://www.hakai.org/>

**Comment by johngillham** [comment]
I'd like to second willhakai's find on "When I run the script on line features, it doesn't seem to bring the update lines into the target features.".  I'm running into the same issue...tested on multiple line featureclass datasets.  It copies the rows over, but nothing shows up in the view...almost like it's not coming in with the geometry? Any thoughts on why or how to fix this?  This is SUCH a great tool...would be even more useful if it worked on lines/polys as well.  Thanks for posting it!

**Comment by bnadler** [comment]
That is strange behavior since the tool shouldn't "care" what geometry type it is. To be honest I did not test this with line features but I will investigate and let you know...

Ben Nadler | Esri Professional Services | Technical Analyst – Utilities, Telecom, & Energy
C: 303.884.9323 | O: 303.443.7779 X8278
Sent from my phone


-------- Original message --------

**Comment by wabbitbear** [comment]
Accidentally tagged my pull request for Issue #1, but it was meant to patch this issue.

I was having a similar issue with point geometry not carrying over from the origin feature class to the target feature class, and it appears to depend on the capitalization of the shape field ("Shape" versus "SHAPE").

**Comment by bnadler** [comment]
wabbitbear is correct. The shape field capitalization depends on the file format. His changes were merged, marked as closed

**Comment by Heidi888** [comment]
Hi, really useful script, but I'm also having trouble getting this to work with line features -  in the output the Shape_Length field is empty and no features are displayed, did you have any luck getting this to work with lines too?

**Comment by bnadler** [comment]
I tested with lines and did not encountered an error.

I believe the issue was related to the shape field name not matching between source and destination databases. Verify that the field names match.

If still coming out empty, please send me a sample to test with.

[cid:storage_emulated_0_DCIM_image002_png_1454429193608]  |  Sent from my phone


-------- Original message --------
