### ISSUE TITLE
Field Issue - REL_GLOBALID vs. REL_OBJECTID

### ISSUE THREAD

**Issue by tjmichael81** [bnadler/Append-Features-With-Attachments#5]
If feature attachments are added to a feature class that does not have a 'GlobalID' field, the attachment table will contain a 'REL_OBJECTID' field rather than a 'REL_GLOBALID' field.  This will cause issues when running this tool, as the value for 'REL_GLOBALID' is assigned in many places, such as:

`expression = buildWhereClauseFromList(tfc,"REL_GLOBALID",guidDict.keys())`

I was working with empty attachment tables so was able to remove and recreate them, after which the tool worked as expected.  Removing and recreating attachment tables may not be an option for everyone, though.

**Comment by bnadler** [comment]
Good to know. Changing the field name on lines 115 and 121 would resolve this.
